language: python
python:
    - "3.3"
    - "2.7"

env:
  global:
    - GAE=${HOME}/.cache/google_appengine
    - API_CHECK=https://appengine.google.com/api/updatecheck

before_script:
# Idea from https://blog.bekt.net/p/gae-sdk/
- SDK_VERSION=$(curl -s $API_CHECK | awk -F '\"' '/release/ {print $2}')
- SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$SDK_VERSION.zip
- echo Installing GAE Python SDK $SDK_VERSION
- wget $SDK_URL -nv
- unzip -q google_appengine_$SDK_VERSION.zip -d ${HOME}/.cache

install:
    - "pip install -r test-requirements.txt"
script:
    - "make test"
notifications:
    email: false
